name: Lint

on: 
 push:
  branches: [master]
 pull_request:
  branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install modules for eslint
      run: npm ci
    - name: Run eslint
      run: npm run lint
